<?php
/**
 * PropelDataCollector.
 *
 * Collects data generated by propel logs
 * You need to be sure that Propel is configured properly
 * Only when there is logger created by Propel we have possibility to "listen"
 * logged messages and collect them.
 *
 *
 * @author Łukasz Wojciechowski <luwo@appflower.com>
 */
class PropelDataCollector extends Symfony\Component\HttpKernel\DataCollector\DataCollector
{
    private $active = false;
    private $queries = array();

    public function __construct() {
        $this->active = Propel::hasLogger();
        if ($this->active) {
            sfContext::getInstance()->getEventDispatcher()->connect('application.log', array($this, 'applicationLog'));
        }
    }

    function applicationLog(sfEvent $event)
    {
        if (!$this->active) {
            return;
        }

        $subject = $event->getSubject();

        if ($subject instanceof sfPropelLogger) {
            $parameters = $event->getParameters();
            $logMessage = $parameters[0];
            $this->queries[] = $logMessage;
        }
    }

    public function collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, \Exception $exception = null)
    {
        $this->data = array(
            'queriesCount' => count($this->queries),
        );
    }

    public function getName()
    {
        return 'propel';
    }
}
